---
repos:
  # isort: Sort imports automatically
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use the latest version of isort
    hooks:
      - id: isort
        args: ["--profile=black"]

  # black: Code formatter
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest version of Black
    hooks:
      - id: black

  # flake8: Linting for Python
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest version of Flake8
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

  # autoflake: Remove unused imports and variables
  - repo: https://github.com/myint/autoflake
    rev: v2.2.1  # Replace with the latest version
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports",
               "--remove-unused-variables", "--in-place"]


  # Check YAML files for syntax errors
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint

  # Check for large files accidentally committed
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
